### ISSUE TITLE
IDM issue

### ISSUE THREAD

**Issue by hemlok89** [thorio/KGrabber#23]
Hello, I have been using this script over the old one & it works awesome. I have just one request to change the way IDM bat file is handled. In the old script it was set in a way that all the links would be added in the scheduler & also in a default folder. But in this script all the files are added all at once with download windows in foreground.

The old script was like [this](https://pastebin.com/9VBRAvNY)

[Here](https://www.internetdownloadmanager.com/support/command_line.html) is the documentation for IDM arguements

**Comment by thorio** [comment]
Try adding `/a` to your IDM arguments in the script's settings.

**Comment by hemlok89** [comment]
Thank you. This works.

**Comment by thorio** [comment]
Should this be the default in future versions?

**Comment by thorio** [comment]
Added this as default value in 3436f6b2a962059bcc16c735998d5fc214e8a515.

**Comment by hemlok89** [comment]
Thank you! This script is really fast compared to the old one. One more request, can you add a `GM_AddSetting` menu for quality selector?

**Comment by thorio** [comment]
@hemlok89, did you see #26?
