### ISSUE TITLE
[feature request] "enter" to complete process 

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#3]
would it be possible to be able to hit "enter" to finish the process?

I tried adding that feature myself, but I don't think I added the right code, to the right place, if you know what I mean.

what I mean is , when you want to watch multiple episodes in a row, so you tell it to get the links for, episode 341-345, I use my keyboard for that, select the first box, type 341, hit tab, type 345, and then hit enter, but nothing happens, and I remember that I have to click the button to complete the from and start the ripping process.

it would be a big help if hitting enter, while in the kissgrabber "form" anyway, also did the same thing as clicking the button.

**Comment by thorio** [comment]
I don't know why I didn't add that before, thanks for pointing it out.

**Comment by thorio** [comment]
You said you tried adding it yourself but failed, so here's what I did:
```
$("#KG-input-from").on("keydown", (e) => {
  if (e.keyCode == 13) {
    $("#KG-input-start").click();
  }
});
```
Add a `keydown` event to the input box, check if the pressed key is enter and then click the start button.

**Comment by stapuft** [comment]
lol thats why it didn't work, I used 
`addEventListener('keypress', (event)=>{`
instead of
`$("#KG-input-from").on("keydown"`

you rule man.
