### ISSUE TITLE
just an FYI really, rapidvideo, nova, and "no capcha"

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#30]
they recently essentially removed rapidvideo links from the site, but in doing so left the "&s=rapidvideo" that skips the capcha enabled, but it directs you to "nova" now, so if you added that bit of code into the nova section, it would become a "no capcha" method as well.

**Comment by thorio** [comment]
Wow, thanks for bringing this up!
Might be slightly dodgy to get this behaviour from the current code but well worth a bodge I'd say.

**Comment by thorio** [comment]
I pushed an update to allow this.
I suspect this will be patched soon, so enjoy it while it lasts. Use 'RapidNova'.

**Comment by thorio** [comment]
I just realized that I forgot to change the actions. Getting direct links for RapidNova should work now.

**Comment by stapuft** [comment]
no worries, I honestly didn't expect such a fast update, and no worries, I just happened to stumble upon this solution when I remembered how I used to skip the capcha, glad I could be of service, also thanks for such an amazing userscript!

**Comment by stapuft** [comment]
works great! hopefully they leave this alone, I mean every other time they update the site they leave the old stuff there, without really changing it.....so....heres to hoping! lol.

**Comment by thorio** [comment]
And just like that, they fixed it :(

**Comment by stapuft** [comment]
fuck that sucks.....why can't they ever listen to me when it comes to actually improving the site? they only ever listen to me point out flaws that get past their bullshit, minimally fixing only things that lose them money.....(nova, or novel planet, is another one of the "kiss media" sites owned by the same guy that owns the others)
