### ISSUE TITLE
Kimcartoon, try to get multiple episodes, cloudflare loop

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#31]
**Describe the bug**
on kimcartoon, say for example a short show where you can feasibly watch 10 episodes before hitting a timeout error, like, https://kimcartoon.to/Cartoon/Transformers-Cyberverse-Season-2
do just that, try to get all the episodes at once, and on the final episode you tell it to do, instead of actually loading the episode, it will stick you into a constant loop of "please wait cloudflare protection services" in order to get out of it you have to completely close the tab, and open a new one, then navigate back to the show page, reopening the closed tab continues the reload loop, and navigating away manually, (via the address bar) in the same tab, back to the show page, or the Kimcartoon main page, keeps you in the reload loop

**Information**
1. Browser: Firefox 70.0.1 (64-bit)
2. Userscript Manager: tampermonkey
3. Show, Episode: https://kimcartoon.to/Cartoon/Transformers-Cyberverse-Season-2
4. Server: any

**Additional context**
I'm not sure, but I think this might have something to do with the speed of the process? like its happening too fast, and the cloudflare protection kicks in? I have no clue what causes it, but I've only managed to hit the problem when i try to get multiple episodes at once, sometimes I'm lucky and can sneak away with 2 videos at once, but never more than 2 on kimcartoon.

**Ps**
also this is kind of a feature request, would a user customizable "delay timer" be a possibility? as in a user customizable timer to delay the process between getting the video link on one episode page, and trying to go to the next episode, (0=default setting and keeps things flowing like they do now, and then the user can put in any number other than 0 to add that delay, in seconds) mainly to help with compatibility with MALsync, your script gets the links faster than it can detect that you are watching/have watched the episodes, its not really a big deal, just a thing I'm only thinking of now, as an afterthought to the actual problem based on the timing aspect possibly being shared between the two.

**Comment by thorio** [comment]
I was unable to reproduce on firefox or chrome, it just goes through all episodes and works normally. Have you tried disabling all extensions/scripts beside Tampermonkey and KissGrabber?

**Comment by stapuft** [comment]
no I havnt, I havnet never had a problem with a userscript like that before, lemme check that I guess it wouldn't hurt to restart my computer either.

**Comment by stapuft** [comment]
@thorio I guess an extension or userscript was blocking the capcha page? I didn't even know kimcartoon had a capcha page? but its working now. thank you.

**Comment by thorio** [comment]
Weird. Out of curiosity, did you figure out what specifically was causing the issue?

**Comment by stapuft** [comment]
nope, i recently re-enabled all my extensions and tried again, and it worked fine again, I'm guessing it was just my shitty computer doing something wrong, it has worked fin since the restart.

**Comment by thorio** [comment]
![have you tried turning it off an on again?](https://i.imgur.com/j880FqN.jpg)
😄

**Comment by stapuft** [comment]
(I fucking love the I.T. crowd)
exactly, when all else fails, RTFM.
sometimes the simplest things just slip past our minds while we do more complex things because of reasons...brains are weird, especially when the sleep tank is running on empty
