### ISSUE TITLE
add a delay?

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#33]
**Is your feature request related to a problem? Please describe.**
there is a mall incompatibility issue with MALsync where the automatic updating of episodes that have been watched isn't updated when using Kgrabber, I tried adding a delay to the script using "await KG.timeout(8);", but that didn't actually add a delay to the script

**Describe the solution you'd like**
a way to add a delay, or a temporary pause, on the Kgrabber script inbetween grabbing episode links, or possibly on the final link (of the range I have chosen, so say I want episodes 1-4, the pause would happen on page 4), so that MALsync can detect that I have watched that episode, or at least the last episode (in the range I picked), so that I don't have to manually do so for each episode/series

**Additional context**
MAlsync-https://github.com/lolamtisch/MALSync

**Comment by thorio** [comment]
The argument for `KG.timeout` is in milliseconds, so 8 won't really do much.
I've also commented on lolamtisch/MALSync#235.

**Comment by stapuft** [comment]
i feel stupid as fuck LOL no wonder I didn't notice anything LOL you rule man, thanks for the help.
