### ISSUE TITLE
something happened, script no longer works. at all.

### ISSUE THREAD

**Issue by stapuft** [thorio/KGrabber#34]
**Describe the bug**
I guess they updated the site or something, I have restarted my browser and computer multiple times, I downgraded the user script back 2 versions but still it doesn't work anymore. none of the extra things appear, and upon checking the debugger it looks like they didn't even run??

without adblocker , and script running.
![image](https://user-images.githubusercontent.com/46431157/68826589-853fb180-066c-11ea-87fe-995d4e4cc105.png)

with adblocker, and script running
![image](https://user-images.githubusercontent.com/46431157/68826622-a43e4380-066c-11ea-87b0-95f3be86ebc5.png)

**Information**
1. Browser: 70.0.1 (64-bit)
2. Userscript Manager: tampermonkey 4.9.6091
3. Show, Episode: any, and all

**Additional context**
tampermonkey just updated as well......so it might be a problem there? but my other userscripts still work...

**Comment by thorio** [comment]
I tested on firefox 70.0.1, Tampermonkey v4.9.5941, and it's working just fine.
It's even working on Tampermonkey beta v4.9.6088.

Please provide more info:
- take a screenshot of the console (F12)
- check the tampermonkey icon; there should be a number next to it showing the number of scripts running

**Comment by stapuft** [comment]
upon further testing it was indeed a problem with tampermonkey, closing this now. sorry for the trouble.
