### ISSUE TITLE
Add beta3 server

### ISSUE THREAD

**Issue by pri-pro** [thorio/KGrabber#37]
Recently kissanime have added beta3 server. Can it be added?

**Comment by thorio** [comment]
Theoretically: yes. Practically: I can't find the links, and beta is broken too.
So just go with Nova for now, they're both behind the captcha anyway.

**Comment by thorio** [comment]
Beta3 has since been removed. There are other new beta servers available: Beta360P and Beta5.

**Comment by thorio** [comment]
Beta360P and Beta5 added in 235bd67.
