### ISSUE TITLE
Beta servers are broken

### ISSUE THREAD

**Issue by thorio** [thorio/KGrabber#38]
**Describe the bug**
Beta servers only ever yield the same links, which is from a comment in KA's js.

**Comment by thorio** [comment]
When this is fixed, the beta3 server should be added. See #37.

**Comment by Dishit79** [comment]
Are you fixing this?

**Comment by thorio** [comment]
Yes, I have already found a solution. I'll probably finish it up and push it to dev sometime tomorrow.
