### ISSUE TITLE
Add support kissanime.nz

### ISSUE THREAD

**Issue by minhngoc25a** [thorio/KGrabber#39]
Could you add support for new domains of KissAnime?

* kissanime.nz
* kissanime.ru.com
* kissanime.ac

Thank you!

**Comment by thorio** [comment]
Looking this over quickly:
- .ru.com is too different, this script is not suited for it.
- .ac redirects to .nz
- .nz look promising, I'll try to make it work.

**Comment by Dishit79** [comment]
We will be waiting for kissanime.nz

**Comment by thorio** [comment]
It is not happening anytime soon, at least not by me.
I took a look at it again and the obfuscation is beyond my abilities or free time, and it's not like i know what to do with the streamx.me links anyway.
If anyone wants to take a crack at it however, be my guest.

**Comment by minhngoc25a** [comment]
Site closed.
