### ISSUE TITLE
Automatic actions don't display buttons

### ISSUE THREAD

**Issue by srajagop** [thorio/KGrabber#42]
**Describe the bug**
Not able to grab the source from kissanime.ru in chrome and firefox.

**Information**
1. Browser: Chrome and Firefox
2. Userscript Manager: tampermonkey
3. Show, Episode: eyeshield 21
4. Server: beta

**Additional context**

**Comment by thorio** [comment]
It works just fine for me (Chrome 81.0.4044.138, Tampermonkey 4.9, KGrabber 3.2), it gets the link and i can download it.
Do you have any additional info that could help to reproduce the issue?

**Comment by srajagop** [comment]
I am attaching a screenshot.

I get a link when I click extract link and choose a server

![issue1](https://user-images.githubusercontent.com/11360377/81467637-e5805d80-918e-11ea-9e94-6dd7ff24134a.PNG)

And then when I visit the link. I get this error

![issue2](https://user-images.githubusercontent.com/11360377/81467646-f204b600-918e-11ea-92d3-f9fcf5433694.PNG)


I think everything is latest versions in mine. I installed it only a couple of days back.

**Comment by thorio** [comment]
Ah, now I understand the problem. It seems you have turned off automatic actions in the compatibility settings. It should still show you a "decrypt" button to do it manually, but I must have broken that a couple of versions ago.

For the moment just go ahead and turn automatic actions on, I will push a patch later today.

**Comment by Dishit79** [comment]
Same thing is happening to me.

**Comment by thorio** [comment]
It should be working now. Is your script up to date? (3.2.1)
