### ISSUE TITLE
How to extract download links from a TXT, JSON or CSV file?

### ISSUE THREAD

**Issue by eslamsidereel** [thorio/KGrabber#48]
I love this script. I mainly used it with `IDM`. But sometimes my internet connection drops from a moment and I have to reload the page then extract the links and solve all the capatcha then re-extract the download links from the URL list.

There is an option to export the URL list to a TXT, JSON or CSV file before extracting the download links.

How can I extract the download links from a TXT, JSON or CSV file, In case my connection dropped again?
I remember that `FFmpeg` can do this,but I searched a lot and couldn't find anything.

I hope someone knows how to do this. And is there a way to use `KGrabber` to re-extract the download links from the URL list externally?

Thanks and sorry for my bad English.

**Comment by KartikSoneji** [comment]
Hi @eslamsidereel 
> But sometimes my internet connection drops from a moment and I have to reload the page then extract the links and solve all the capatcha then re-extract the download links from the URL list.

> How can I extract the download links from a TXT, JSON or CSV file, In case my connection dropped again?
I remember that FFmpeg can do this,but I searched a lot and couldn't find anything.

Sorry, I am not sure that I understand what you mean.
Can you please rephrase the question?
Pictures will help : )

If you want to import the download links into IDM then you can do that from a txt file as [described here](https://www.internetdownloadmanager.com/support/import_downloads.html).

**Comment by thorio** [comment]
As long as the tab is still open you should be able to hit `reset` (where `get direct links` was before) to restore the original links.

**Comment by thorio** [comment]
Can this be closed?

**Comment by eslamsidereel** [comment]
yes of course
