### ISSUE TITLE
IDM exporter

### ISSUE THREAD

**Issue by eslamsidereel** [thorio/KGrabber#5]
I love this script. It is simple and easy to use, but i could't figure out how to use the exported json files. I searched a lot but could't find any way to download the video list in json files. Can you make a quick tutorial about how to download video files from the exported json file. I will appreciate that.
Thanks in advance.

**Comment by thorio** [comment]
The JSON export is kind of arbitrary, as JSON is just a general syntax for packaging javascript data into a string. So you can't use it without either having software that expects the specific structure this script spits out or writing such software yourself.

**Comment by eslamsidereel** [comment]
So i can't use json files to download entire video list?

**Comment by thorio** [comment]
You can just export as a list and feed that to a download manager, but that won't preserve the episode numbers.
The aria2c option should work, but it's a command line tool and i've found it to be quite slow compared to other download managers.
IDM has a import feature, but I haven't gotten around to examining it yet. Depending on the format it could be possible to add an exporter for it.
What download manager do you use, and what ways does to it have to add multiple files at once?

**Comment by eslamsidereel** [comment]
I use IDM but the process is quite long so i was looking for a faster way to download them. I prepared a cmd batch file like the following
"C:\Program Files (x86)\Internet Download Manager\idman.exe" /n /p "D:\Anime\XXX" /a /f "[Kissanime] XXX - 01 [360].mp4" /d "
"XXX" name of the anime
 I export all episodes as a list then i have to do the links and the numbering manually.

**Comment by thorio** [comment]
I will look into it in the next couple of days.

**Comment by eslamsidereel** [comment]
I am looking forward to it.

**Comment by thorio** [comment]
Turns out the files IDM "exports" only contain the links, not paths or file names etc.
So what I did is create an auto-generator for adding the downloads to IDM via command line.

**Comment by eslamsidereel** [comment]
That would be awesome thanks a lot

**Comment by stapuft** [comment]
> 
> 
> Turns out the files IDM "exports" only contain the links, not paths or file names etc.
> So what I did is create an auto-generator for adding the downloads to IDM via command line.

@thorio would it be possible to do this for youtube-dl aswell? specifically to grab direct links for streaming purposes?

**Comment by thorio** [comment]
Besides rapidvideo, which the script already supports, only a select few servers work with youtube-dl.
The ones that work are Openload and Streamango, but i don't think they provide something rapidvideo doesn't.

**Comment by stapuft** [comment]
@thorio sometimes rapidvideo decides it wants to play slow, and actually, lol, I tend to use openload then rapid video as my second and third choice, with the beta 2 in fourth place

but so far the servers that support using VLC to play them while streaming are 
rapidvideo
openload
streammango
beta2
beta
nova (novelplanet)

its just for everything except rapidvideo and beta2 you need to click on the link, and then mess with the quality to get the direct link via the "inspect element" dialog or an extension like "youtube-dl" or "play to vlc"

**Comment by thorio** [comment]
If you want an exporter that generates a batch file that then uses youtube-dl to get the links and after that puts everything in a m3u8 playlist with the correct titles etc., that's *very* specific and you're probably the only one who would prefer it exactly that way.
At that point you should just write an exporter yourself, and patch it into the KG.exporters array. The script is specifically written to make this possible without changing any existing code.

**Comment by stapuft** [comment]
I was honestly just asking for one to get the links, via a simple .bat file for "youtube-dl" I didn't even think so far ahead as to make a Playlist with the links, when rapidviedo goes down I tend to do things one link at a time, which is where it gets tedious. I wasnt suggesting changing any exporters??

**Comment by thorio** [comment]
So you just want a way to get direct links from openload and streamango?

**Comment by stapuft** [comment]
if possible, it would make things simpler and alot less tedious to just be able to click a button or two than to have to type out a string of commands every time, thats one of the reasons I hate CMD line programs so much, although now with the "clipboard" being built into windows 10 (can have multiple separate items stored in it like you can on mobile phones.) it makes it easier...just not by much

**Comment by thorio** [comment]
I really don't get why it's too much work to open cmd, type out `youtube-dl -g` and paste the link.
Anyway, the reason I don't want to add this is because it gums up the exporter list.

I looked into adding a direct link action for openload and streamango, but there's no nice clean solution like with rapidvideo. It would require going to the embed page and generating a fake click, which is prone to breaking if something on their side changes.

If you really want to save the 10 seconds it takes to use youtube-dl, you can write your own exporter. See the [list exporter](https://github.com/thorio/KGrabber/blob/e55b8e8f18af15a579b0bdcd2a2762664e7db863/src/js/exporters.js#L4-L16) for an easy example.

**Comment by stapuft** [comment]
just because you have a hard on for the cmd line doesn't mean everyone does, again thank you for the awesome addon, have a great day.
