### ISSUE TITLE
KissAnime Anti-Adblock Blocker on kimcartoon.to

### ISSUE THREAD

**Issue by shinji257** [thorio/KGrabber#8]
Can we get support for this site?

**Comment by thorio** [comment]
Excerpt from the repository's readme:
![image](https://user-images.githubusercontent.com/39875034/60388630-b9974480-9ab4-11e9-8701-3679600562bd.png)
It is supported, does it not work for you?

**Comment by shinji257** [comment]
I totally missed that event thought I stared right at it too before posting.  No it isn't but after some digging I found that it is conflicting with this script on the website.

https://greasyfork.org/en/scripts/4900-kissanime-anti-adblock-blocker

The scripts work fine together over on kissanime.ru so I don't know which script needs adjusted to accommodate the other.

**Comment by thorio** [comment]
The weird thing is that i also use that script, and I haven't found issues on any of the sites.
Please provide more info: the show, server and episodes, and also anything else that can help to reproduce the issue.

**Comment by shinji257** [comment]
This is one of many URLs where it failed to load with the combination above.

https://kimcartoon.to/Cartoon/Gargoyles

It is this specific site only though.

**Comment by thorio** [comment]
Tried eps 1-3 from rapidvideo and it works just fine. Strange.

**Comment by shinji257** [comment]
Ok.  Maybe I'm just looking in the wrong place then.

I tried it in a portable Firefox install to isolate things and it was just that extension, your script, and the seemingly conflicting script and I was able to reproduce the issue.

Failure check:
Browser: Firefox 67.0.4
Tampermonkey 4.9.5941

Works fine in Chrome with both an older stable and current beta version
Browser: Google Chrome 75.0.3770.100
Tampermonkey 4.8.41 and 4.9.5941 (The beta version)

**Comment by thorio** [comment]
I found the issue: for some reason, the anti-adblocker script is blocking jquery, which is required for KissGrabber to work.

**Comment by thorio** [comment]
for now this can be fixed by adding
```javascript
/* fix for KissGrabber; don't block jquery */
if (element_host === 'code.jquery.com')
    return;
```
on line 35 of the anti-adblock script.

**Comment by shinji257** [comment]
Thanks for this fix!  Now I just have to figure out why that script breaks GP/GUS hosted videos.  Once again it works fine in Chrome.  😡

**Comment by shinji257** [comment]
Ok.  I went back and did some debugging and I found the issue in the script that is breaking Firefox compatibility.  It is actually the same issue that is preventing your script from kicking in and breaking GP/GUS so adding those lines are not really needed unless we want to do whitelisting.

Commending out lines 36 and 37 (seem to just block disqus?) took care of both issues without needing to explicitly block jQuery.  On Chrome Disqus loads just fine (which also relies on jQuery) but on Firefox it fails.  Commenting out or removing those lines allows Disqus to load and I guess jQuery ends up coming in with it as well.

Not sure why the script was blocking Disqus at all.  Sorry I wasted your time with essentially debugging someone else's script.  I'll report the fix on their greasyfork page and maybe someday it will get patched in there.

**Comment by thorio** [comment]
It just blocks any cross-origin script except disqus. Which is partially good because it blocks trackers and ad scripts, but it also blocks jquery and video.js. You can explicitly allow video.js like jquery but with 'vjs.zencdn.net' instead.

**Comment by shinji257** [comment]
Ahh ok.  I'm not personally concerned with that because I'm using uBlock Origin here to handle most of that anyways but I'll check and add it to see if that takes care of the issue then also post that version as well.
